# Generated by Django 6.0.1 on 2026-01-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='whatsapp_images/'),
        ),
    ]
