# Generated by Django 6.0.1 on 2026-01-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='contacts',
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField(default=100)),
                ('contacts', models.ManyToManyField(to='whatsapp.contact')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='groups',
            field=models.ManyToManyField(to='whatsapp.contactgroup'),
        ),
    ]
